{{- if and .Values.ingress .Values.ingressHost }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: mosquitto
  annotations:
    # MQTT-over-WebSocket connections are long-lived and idle for long
    # periods. The nginx defaults (60s) will close idle connections,
    # breaking MQTT clients. Set long timeouts.
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    {{- with .Values.ingressAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingressClassName }}
  ingressClassName: {{ .Values.ingressClassName | quote }}
  {{- end }}
  {{- if .Values.ingressTlsSecret }}
  tls:
    - hosts:
        - {{ .Values.ingressHost | quote }}
      secretName: {{ .Values.ingressTlsSecret | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.ingressHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 9001
{{- end }}
