{{- $hasUsers := and (not .Values.allowAnonymous) .Values.users }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-users
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: mosquitto
type: Opaque
stringData:
  passwd: |
    {{- range $username, $user := .Values.users }}
    {{ $username }}:{{ $user.password }}
    {{- end }}
