---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-headless
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: mosquitto
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: mosquitto
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
      protocol: TCP
    {{- if .Values.websocket }}
    - name: mqtt-ws
      port: 9001
      targetPort: mqtt-ws
      protocol: TCP
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: mosquitto
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: mosquitto
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
      protocol: TCP
    {{- if .Values.websocket }}
    - name: mqtt-ws
      port: 9001
      targetPort: mqtt-ws
      protocol: TCP
    {{- end }}
{{- if .Values.external }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-external
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: mosquitto
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: mosquitto
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
      protocol: TCP
    {{- if .Values.websocket }}
    - name: mqtt-ws
      port: 9001
      targetPort: mqtt-ws
      protocol: TCP
    {{- end }}
{{- end }}
