---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        name: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: ghost:6-alpine
      env:
        NODE_ENV: production
        url: {{ .Values.host }}
        admin__url: {{ .Values.admin.url }}
        database__client: {{ .Values.database.client }}
        database__connection__host: {{ .Values.database.connection.host }}
        database__connection__user: {{ .Values.database.connection.user | default "ghost" }}
        database__connection__password: {{ .Values.database.connection.password }}
        database__connection__database: {{ .Values.database.connection.database | default "ghost" }}
        tinybird__tracker__endpoint: {{ .Values.tinybird.trackerEndpoint }}/.ghost/analytics/api/v1/page_hit
        tinybird__adminToken: {{ .Values.tinybird.adminToken }}
        tinybird__workspaceId: {{ .Values.tinybird.workspaceId }}
        tinybird__tracker__datasource: {{ .Values.tinybird.trackerDatasource | default "analytics_events" }}
        tinybird__stats__endpoint: {{ .Values.tinybird.statsEndpoint | default "https://api.tinybird.co" }}
