---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.ghost-application
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
  - name: default
    dependsOn:
    - cozystack.networking
    components:
    - name: ghost
      path: apps/ghost
    - name: ghost-rd
      path: system/ghost-rd
      install:
        namespace: cozy-system
        releaseName: ghost-rd